version: '3.8'

services:
  go:
    build:
      context: go
    command: sleep infinity
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - ~/.ssh:/home/vscode/.ssh
      - ~/.gitconfig:/home/vscode/.gitconfig
